config/routes.rb
Rails.application.routes.draw do
  namespace 'api' do
    namespace 'v1' do
      resources :rooms, only: [:index]
      resources :messages, only: :create
      post "/rooms" => "rooms#create"
    end
  end

  devise_for :users, controllers: { registrations: "registrations" }
  root to: "rooms#index"
  resources :rooms, only: %i[show new create], param: :title
  resources :messages, only: %i[ create ] do
    member { post :like }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :message, counter_cache: true
end

app/models/message.rb
class Message < ApplicationRecord
  has_many :likes, dependent: :destroy
  belongs_to :user
  belongs_to :room

  scope :sorted, -> { order(:id) }
  validates :body, presence: true

  after_create_commit -> {
    broadcast_append_to(
      'toasts',
      target: "toasts",
      partial: 'shared/toast',
      locals: { message: self }
      )
  }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages, -> { sorted }, dependent: :destroy

  validates :title, presence: true, uniqueness: true, length: { minimum: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :messages
  has_many :likes

  devise :database_authenticatable, :registerable,
         :recoverable, :validatable

  def name
    name = email.split('@').first.strip
    return email if name.blank?

    name
  end
end

app/controllers/api/v1/messages_controller.rb
module Api
  module V1
    class MessagesController < ApplicationController
      skip_before_action :verify_authenticity_token

      def create
        room = Room.find_by_title message_params['room_title']
        body = message_params['message']

        if room.blank?
          render json: { room: 'not found' }, status: :not_found
        elsif body.blank?
          render json: { message: 'cant be blank' }, status: :unprocessable_entity
        else
          @message = Message.create(room:, body:, user: guest)
          @message.broadcast_append_to @message.room, locals: { user: guest }
          render json: @message, status: :created
        end
      end

      private

      def message_params
        params.permit(:room_title, :message)
      end

      def guest
        return @guest if @guest
        Rails.cache.write('guest', User.find_by_email('guest@mail.ru'), expires_in: 2.days)

        @guest = Rails.cache.read('guest')
        @guest
      end
    end
  end
end

app/controllers/api/v1/rooms_controller.rb
module Api
  module V1
    class RoomsController < ApplicationController
      skip_before_action :verify_authenticity_token

      def index
        @rooms = Room.order('created_at DESC')
        render json: { status: 'Success', rooms: @rooms }, status: :ok
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @new_message = current_user&.messages&.build(message_params)

    if @new_message&.save
      @new_message.broadcast_append_to @new_message.room, locals: { user: current_user }
    end
  end

  def like
    @message = Message.find(params[:id])

    like = @message.likes.find_by(user: current_user)

    if like.present?
      like.destroy
    else
      @message.likes.create(user: current_user)
    end

    @message.broadcast_replace_to(
      [current_user, @message.room],
      target: "message_#{@message.id}_likes",
      partial: 'messages/heart',
      locals: { user: current_user, message: @message}
    )

    @message.broadcast_replace_to(
      @message.room,
      target: "message_#{@message.id}_likes_count",
      locals: { message: @message},
      partial: 'messages/likes_count',
    )
  end

  private

  def message_params
    params.require(:message).permit(:room_id, :body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def after_sign_up_path_for(resource)
    root_path
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      respond_to do |format|
        format.html { redirect_to rooms_path, flash[:success] = "Room was successfully created." }
        format.turbo_stream { flash.now[:success] = "Room was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @room = Room.find_by!(title: params[:title])
    @messages = @room.messages
    @new_message = current_user&.messages&.build
  end

  private

  def room_params
    params.require(:room).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend 'flash', partial: 'shared/flash'
  end

  def flash_color(key, type, opacity)
    if key == 'success'
      "#{type}-green-#{opacity}"
    else
      "#{type}-red-#{opacity}"
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
  def heart(message, user)
    message.likes.find_by(user: user).present? ? "🧡" :  "🤍"
  end

  def likes_count(message)
    " #{message.likes_count}" if message.likes_count.positive?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbochat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="min-h-full min-w-screen">
      <%= render 'shared/navbar' %>

      <header class="bg-white shadow">
        <div class="px-4 py-6 sm:px-6 lg:px-8 text-center">
          <h1 class="text-3xl font-bold tracking-tight text-blue-700">Test Chat with turbo and web sockets</h1>
        </div>
      </header>

      <main> 
        <%= audio_tag("notification.mp3", id: 'audio') %>
        <div class='flex'>
          <div class='grow-0 shrink-0 self-start w-72 top-13'>
            <div class='flex flex-col' id='toasts'></div>
          </div>

            <div class="grow max-w-7xl py-6 sm:px-6 lg:px-8">
              <div id='flash' class="flash">
                <%= render 'shared/flash' %>
              </div>

              <%= yield %>

              <%= turbo_stream_from('toasts') if current_user %>
            </div>
          </div>
        </div>
      </main>
    </div>
  </body>
</html>

app/views/messages/_heart.html.erb
<%= turbo_frame_tag "message_#{message.id}_likes" do %>
    <span><%= heart(message, user) %></span>
<% end %>

app/views/messages/_likes_count.html.erb
<%= turbo_frame_tag "message_#{message.id}_likes_count" do %>
    <span><%= likes_count(message) %></span>
<% end %>

app/views/messages/_message.html.erb
<div class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600 flex">
  <div class="w-1/12 flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white">
    <div class="font-normal text-gray-500 text-sm"><%= l(message.created_at, format: :short) %></div>
  </div>
  <div class="w-2/12 px-6 py-4"><%= message.user.name %></div>
  <div class="w-8/12 px-6 py-4"><%= message.body %></div>
  <div class="w-1/12 px-6 py-4 flex">
  <%= link_to like_message_path(message), data: { turbo_method: 'post', turbo_frame: '_top' }  do %>
    <%= render partial: 'messages/heart', locals: { user: user, message: message } %>
    <%= render partial: 'messages/likes_count', locals: { message: message } %>
    <% end %>
  </div>
</div>

app/views/rooms/_form.html.erb
<%= turbo_frame_tag room do %>
  <%= form_for room, html: { class: 'max-w-sm mx-auto border-2 rounded-lg border-blue-500 p-6' } do |f| %>
    <%= render partial: 'shared/errors', locals: { object: room } %>

    <div class='mb-1'>
      <%= f.label :title, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    </div>

    <div class='mb-2'>
      <%= f.text_field :title, autocomplete: "title", class: 'shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light' %>
    </div>

    <%= f.submit 'Create Room', class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800'%>
  <% end %>
<% end %>

app/views/rooms/_new_room_link.html.erb
<%= link_to 'New Room', new_room_path, class: 'text-white bg-green-700 max-w-fit hover:bg-green-800 focus:outline-none focus:ring-4 focus:ring-green-300 font-medium rounded-full text-sm px-6 py-3.5 text-center me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800'%>

app/views/rooms/_room.html.erb
<%= link_to room_path(room.title), target: "_blank", rel: "noopener noreffer", class: "block text-center max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700" do %>
  <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= room.title %></h5>
 <% end %>

app/views/rooms/create.turbo_stream.erb
<%= turbo_stream.append "rooms", partial: "rooms/room", locals: { room: @room } %>
<%= turbo_stream.update Room.new, partial: 'rooms/new_room_link' %>
<%= render_turbo_stream_flash_messages %>

app/views/rooms/index.html.erb
<div class='flex flex-col justify-center items-center' >
  <% if user_signed_in? %>
    <%= turbo_frame_tag Room.new do %>
      <%= render 'new_room_link' %>
    <% end %>
  <% end %>

  
  <div id='rooms' class="mt-10 flex gap-7 flex-wrap justify-between aling-center">
    <%= render @rooms %>
  </div>
</div>

<%= turbo_stream_from :rooms %>

app/views/rooms/new.html.erb
<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<div class="relative overflow-x-auto shadow-md sm:rounded-lg h-96" id='chat-container'>
  <div class="w-full text-sm text-gray-500 dark:text-gray-400">
    <div class="sticky top-0 text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400 flex">
      <div class="w-1/12 px-6 py-3">Time</div>
      <div class="w-2/12 px-6 py-3">Email</div>
      <div class="w-8/12 px-6 py-3">Message</div>
      <div class="w-1/12 px-6 py-3">Like count</div>
    </div>
    <div>
      <%= turbo_frame_tag :messages do %>
        <%= render partial: "messages/message", collection:  @messages, locals: { user: current_user } %>
      <% end %>
    </div>
    
    <% if user_signed_in? %>
      <%= form_with(model: @new_message, data: { controller: 'chat-refresh', action: "turbo:submit-end->chat-refresh#clearInput" }) do |f| %>
        <div>
          <div class="mt-2">
            <%= f.text_field :body, autofocus: true, required: true, placeholder: 'Text here', class: "px-4 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
          </div>
        </div>
        <%= f.hidden_field :room_id, value: @room.id %>
      <% end %>
    <% end %>
  </div>
</div>

<%= turbo_stream_from @room %>
<%= turbo_stream_from [current_user, @room] %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <div class="flex items-center p-4 mb-4 text-sm text-red-800 border border-red-300 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400 dark:border-red-800" role="alert">
        <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
        </svg>
        <div>
          <span class="font-medium"><%= message %></span>
        </div>
      </div>
    <% end %>
  </ul>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="bg-green-200 px-6 py-4 mb-4 rounded-md text-lg flex justify-between items-center mx-auto max-w-lg" 
              data-controller='flash-message' data-flash-message-target='flash'>
    <div class='flex items-center justify-start'>
      <svg viewBox="0 0 24 24" class="text-green-600 %> w-5 h-5 sm:w-5 sm:h-5 mr-3">
        <path fill="currentColor"
              d="M12,0A12,12,0,1,0,24,12,12.014,12.014,0,0,0,12,0Zm6.927,8.2-6.845,9.289a1.011,1.011,0,0,1-1.43.188L5.764,13.769a1,1,0,1,1,1.25-1.562l4.076,3.261,6.227-8.451A1,1,0,1,1,18.927,8.2Z">
        </path>
      </svg>
     
      
      <span class="text-green-800 ml-3"><%= value %></span>
    </div>
    
    <button type="button" data-action="click->flash-message#close" class="ml-5 bg-green-200 text-green-500 rounded-lg focus:ring-2 p-1.5 hover:bg-green-400 inline-flex items-center justify-center h-6 w-6">
      <span class="sr-only">Close</span>
      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
      </svg>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="flex h-16 items-center justify-between">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <a href='/'>
            <img class="h-8 w-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
          </a>
        </div>
        <div class="hidden md:block">
          <div class="ml-10 flex items-baseline space-x-4">          
            <% if user_signed_in? %>
              <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
            <% else %>
              <%= link_to "Sign In", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
              <%= link_to "Sign Up", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
            <% end %>        
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="md:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pb-3 pt-2 sm:px-3">
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
      <% end %> 
    </div>
  </div>
</nav>

app/views/shared/_toast.html.erb
<div data-controller='flash-message' data-flash-message-target='flash' class="flex text-gray-500 break-all rounded-lg shadow bg-gray-300 dark:text-gray-400 ml-2 mt-2 p-4" role="alert">
  <div class="ms-3 text-sm font-normal">
    <span class="mb-1 text-sm font-semibold text-gray-900 dark:text-white">
      <%= message.room.title %>
    </span>
    <div class="mb-2 text-sm font-normal">
      <%= message.body %>
    </div> 

    <%= link_to 'Reply', room_path(message.room.title), data: { turbo_frame: '_top' }, class: 'inline-flex px-2.5 py-1.5 text-xs font-medium text-center text-white bg-blue-600 rounded-lg hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-800' %>
  </div>
  <button type="button" data-action="click->flash-message#close" class="ms-auto -mx-1.5 -my-1.5 bg-gray-300 justify-center items-center flex-shrink-0 text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-message-cta" aria-label="Close">
    <span class="sr-only">Close</span>
    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
    </svg>
  </button>
</div>